spring:
  application:
    name: shared
  cloud:
    aws:
      region:
        static: ${AWS_REGION:sa-east-1}
      credentials:
        use-default-provider-chain: true
      s3:
        region: ${AWS_REGION:sa-east-1}
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}